Repository groundhog2k/helm-charts, pull requests merged in 2021-01, with the labels that each got.

#163 Updated mongodb chart to support user database creation
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/templates/customconfig.yaml
  charts/mongodb/templates/initdbconfig.yaml
  charts/mongodb/templates/inituserdb.yaml
  charts/mongodb/templates/secureconfig.yaml
  charts/mongodb/templates/statefulset.yaml
  charts/mongodb/values.yaml
Labels: enhancement

#174 Updated ghost to 3.40.5
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#180 Fixes issue with missing fsGroup
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/values.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/values.yaml
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/values.yaml
Labels: bug

#186 Updated nextcloud image to 20.0.5
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
Labels: update

#188 Improved post-upgrade control for Nextcloud chart
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/templates/post-upgrade.yaml
  charts/nextcloud/templates/scripts.yaml
  charts/nextcloud/values.yaml
Labels: feature, improvement

#190 Updated chart for RabbitMQ 3.8.10
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#184 Update MariaDB chart to avoid overwriting root and user DB passwords …
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/templates/secureconfig.yaml
Labels: feature

#193 Fixed issues #192, #191, #169 for RabbitMQ
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/templates/secrets.yaml
  charts/rabbitmq/templates/statefulset.yaml
  charts/rabbitmq/values.yaml
Labels: bug, feature, improvement

#194 Fixed issues #192, #191, #169 for Redis
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/templates/statefulset.yaml
  charts/redis/values.yaml
Labels: bug, feature, improvement

#195 Fixed issues #192, #169 for Postgres
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/templates/customconfig.yaml
  charts/postgres/templates/inituserdb.yaml
  charts/postgres/templates/secureconfig.yaml
  charts/postgres/templates/statefulset.yaml
  charts/postgres/values.yaml
Labels: feature, improvement

#196 Fixed issues #192, #191, #169 for MongoDB
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/templates/customconfig.yaml
  charts/mongodb/templates/inituserdb.yaml
  charts/mongodb/templates/secureconfig.yaml
  charts/mongodb/templates/service-internal.yaml
  charts/mongodb/templates/statefulset.yaml
  charts/mongodb/values.yaml
Labels: bug, feature, improvement

#197 Fixed issues #192, #169 for MariaDB
  .gitignore
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/templates/secureconfig.yaml
  charts/mariadb/templates/statefulset.yaml
  charts/mariadb/values.yaml
Labels: feature, improvement

#199 Fixed missing headless service
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/templates/service-internal.yaml
  charts/mariadb/templates/statefulset.yaml
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/templates/service-internal.yaml
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/templates/service-internal.yaml
  charts/postgres/templates/statefulset.yaml
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/templates/service-internal.yaml
  charts/redis/templates/statefulset.yaml
Labels: bug

#200 Fixed issues #192, #191, #169 for Elastic
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/templates/statefulset.yaml
  charts/elasticsearch/values.yaml
Labels: bug, feature, improvement

#201 Fixed issues #192, #191, #169 for Graylog
  charts/graylog/Chart.lock
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/charts/elasticsearch-0.1.0.tgz
  charts/graylog/charts/elasticsearch-0.1.1.tgz
  charts/graylog/charts/mongodb-0.2.7.tgz
  charts/graylog/charts/mongodb-0.2.9.tgz
  charts/graylog/templates/_helpers.tpl
  charts/graylog/templates/geoipsecrets.yaml
  charts/graylog/templates/secureconfig.yaml
  charts/graylog/templates/statefulset.yaml
  charts/graylog/values.yaml
Labels: bug, feature, improvement

#203 Updated rabbitmq chart for RabbitMQ 3.8.11
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/templates/secrets.yaml
  charts/rabbitmq/values.yaml
Labels: update

#204 Fixed issues #192, #169 for commento chart
  charts/commento/Chart.lock
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/charts/postgres-0.2.5.tgz
  charts/commento/charts/postgres-0.2.7.tgz
  charts/commento/templates/_helpers.tpl
  charts/commento/templates/deployment.yaml
  charts/commento/templates/secrets.yaml
  charts/commento/templates/secureconfig.yaml
  charts/commento/values.yaml
Labels: feature, improvement

#206 Updated ghost chart for Ghost 3.41.1
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#208 Updated ghost to 3.41.2
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#210 Updated nextcloud to 20.0.6
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
Labels: update

#213 Updated graylog to 4.0.2
  charts/graylog/Chart.yaml
  charts/graylog/README.md
Labels: update

#215 Fix issue #214
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/templates/statefulset.yaml
Labels: bug
