Repository groundhog2k/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#539 Update graylog chart for Graylog 4.1.2
  charts/graylog/Chart.yaml
  charts/graylog/README.md
Labels: update

#540 Update rabbitmq helm chart for RabbitMQ 3.9.1
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#541 Added service type from values.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/templates/service.yaml
Labels: bug

#545 Update ghost chart for Ghost 4.11.0
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#547 Update gitea chart for Gitea 1.14.6
  charts/gitea/Chart.yaml
  charts/gitea/README.md
Labels: update

#550 Update gitea chart for Gitea 1.14.6 (#547)
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/values.yaml
Labels: update

#554 Update rabbitmq chart for RabbitMQ 3.8.21
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#555 Update rabbitmq chart for RabbitMQ 3.9.3
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#562 Update mongodb chart for MongoDB 4.4.8
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
Labels: update

#563 Update mariadb chart for MariaDB 10.5.12
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
Labels: update

#564 Update postgres chart for Postgres 13.4
  charts/postgres/Chart.yaml
  charts/postgres/README.md
Labels: update

#566 Update chart dependencies
  charts/ghost/Chart.lock
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/charts/mariadb-0.2.13.tgz
  charts/ghost/charts/mariadb-0.2.14.tgz
  charts/gitea/Chart.lock
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/charts/mariadb-0.2.13.tgz
  charts/gitea/charts/mariadb-0.2.14.tgz
  charts/gitea/charts/postgres-0.2.11.tgz
  charts/gitea/charts/postgres-0.2.13.tgz
  charts/graylog/Chart.lock
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/charts/mongodb-0.3.2.tgz
  charts/graylog/charts/mongodb-0.3.3.tgz
  charts/nextcloud/Chart.lock
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/charts/mariadb-0.2.13.tgz
  charts/nextcloud/charts/mariadb-0.2.14.tgz
  charts/nextcloud/charts/postgres-0.2.11.tgz
  charts/nextcloud/charts/postgres-0.2.13.tgz
  charts/wordpress/Chart.lock
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/charts/mariadb-0.2.13.tgz
  charts/wordpress/charts/mariadb-0.2.14.tgz
Labels: update

#568 Update Commento chart dependency
  charts/commento/Chart.lock
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/charts/postgres-0.2.10.tgz
  charts/commento/charts/postgres-0.2.13.tgz
Labels: update

#570 Commento Origin
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/templates/_helpers.tpl
  charts/commento/values.yaml
Labels: improvement

#572 Update ghost chart for Ghost 4.12.1
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#574 Update nextcloud chart for Nextcloud 22.1.0
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
Labels: update

#575 Update rabbitmq chart for RabbitMQ 3.9.4
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#577 Update gitea chart for Gitea 1.15.0
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/templates/scripts.yaml
Labels: update

#582 Update rabbitmq chart for RabbitMQ 3.8.22
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#583 Update rabbitmq chart for RabbitMQ 3.9.5
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#584 Update nextcloud chart for Nextcloud 22.1.1
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
Labels: update

#585 gitea chart always sets sqlite3 as DB_TYPE
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/templates/secureconfig.yaml
  charts/gitea/values.yaml
Labels: feature
