Repository groundhog2k/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#769 add service annotations support. Closes #768
  charts/remark42/Chart.lock
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/charts/redis-0.4.8.tgz
  charts/remark42/charts/redis-0.4.9.tgz
  charts/remark42/templates/service.yaml
  charts/remark42/values.yaml
Labels: improvement

#780 Improve all charts to support service annotations
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
Labels: improvement

#781 Update graylog chart from Graylog 4.2.5
  charts/graylog/Chart.yaml
  charts/graylog/README.md
Labels: update

#783 Upgrade rabbitmq chart for RabbitMQ 3.8.27
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#784 Update rabbitmq chart for RabbitMQ 3.9.12
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
Labels: update

#788 Update mongodb chart for MongoDB 5.0.x
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
Labels: update

#789 Update mariadb chart to support MariaDB 10.6.x
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
Labels: update

#790 Update mariadb chart for MariaDB 10.7.x
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
Labels: update

#792 Update wordpress chart for Wordpress 5.8.3
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/templates/extendedconfig.yaml
Labels: update

#794 Update ghost chart for Ghost 4.32.1
  charts/ghost/Chart.yaml
  charts/ghost/README.md
Labels: update

#797 Update remark42 chart for Remark42 V1.9.0
  charts/remark42/Chart.yaml
  charts/remark42/README.md
Labels: update

#802 Update elasticsearch chart for Elasticsearch 6.8.23
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
Labels: update

#803 Update elasticsearch chart for Elasticserach 7.16.3
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
Labels: update

#804 Update remark42 chart to support new configuration options
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/templates/_helpers.tpl
  charts/remark42/templates/deployment.yaml
  charts/remark42/values.yaml
Labels: update

#807 Update gitea chart for Gitea 1.15.10
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
Labels: update

#810 fix: #809
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/templates/ingress.yaml
Labels: bug

#813 [postgres] issue with authMethod: "md5"
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/templates/customconfig.yaml
  charts/postgres/templates/statefulset.yaml
Labels: bug

#814 Fixed issue #811
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/RELEASENOTES.md
Labels: bug

#816 Fix ingress apiVersion detection
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/RELEASENOTES.md
  charts/commento/templates/deployment.yaml
  charts/commento/templates/ingress.yaml
  charts/commento/values.yaml
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
  charts/elasticsearch/templates/ingress.yaml
  charts/elasticsearch/templates/statefulset.yaml
  charts/elasticsearch/values.yaml
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
  charts/ghost/templates/deployment.yaml
  charts/ghost/templates/ingress.yaml
  charts/ghost/values.yaml
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
  charts/gitea/templates/ingress.yaml
  charts/gitea/templates/post-install.yaml
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/templates/ingress.yaml
  charts/graylog/templates/statefulset.yaml
  charts/graylog/values.yaml
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
  charts/nextcloud/templates/cronjobs.yaml
  charts/nextcloud/templates/customconfigshook.yaml
  charts/nextcloud/templates/defaultcronjobs.yaml
  charts/nextcloud/templates/ingress.yaml
  charts/nextcloud/templates/postupgradehook.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/ingress.yaml
  charts/rabbitmq/templates/statefulset.yaml
  charts/rabbitmq/values.yaml
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/RELEASENOTES.md
  charts/remark42/templates/ingress.yaml
Labels: bug

#817 Fixed issue #816
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
Labels: bug

#818 Fix issue #816
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
Labels: bug

#819 Update rabbitmq chart for RabbitMQ 3.9.13
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
Labels: update

#820 Update ghost chart for Ghost 4.32.3
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#822 Services refuse to chart due to bug in new startupProbe
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/templates/deployment.yaml
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
  charts/elasticsearch/templates/statefulset.yaml
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
  charts/ghost/templates/deployment.yaml
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/templates/statefulset.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/statefulset.yaml
Labels: bug

#823 Fixed issue #821
  charts/commento/RELEASENOTES.md
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
Labels: bug

#824 Fixed #821
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/RELEASENOTES.md
Labels: bug

#825 Fixes issue #821
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
Labels: bug

#826 Add support for startupProbe to all charts
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/RELEASENOTES.md
  charts/mariadb/templates/statefulset.yaml
  charts/mariadb/values.yaml
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/RELEASENOTES.md
  charts/mongodb/templates/statefulset.yaml
  charts/mongodb/values.yaml
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/RELEASENOTES.md
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/RELEASENOTES.md
  charts/redis/templates/statefulset.yaml
  charts/redis/values.yaml
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
  charts/wordpress/templates/deployment.yaml
  charts/wordpress/values.yaml
Labels: feature, improvement

#827 Added startup probe #826
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/RELEASENOTES.md
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/RELEASENOTES.md
Labels: feature, improvement

#828 Added startup probe #826
  charts/mariadb/Chart.yaml
  charts/mariadb/README.md
  charts/mariadb/RELEASENOTES.md
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/RELEASENOTES.md
Labels: feature, improvement

#830 Update chart dependencies
  charts/commento/Chart.lock
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/RELEASENOTES.md
  charts/commento/charts/postgres-0.2.15.tgz
  charts/commento/charts/postgres-0.2.16.tgz
  charts/ghost/Chart.lock
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
  charts/ghost/charts/mariadb-0.2.16.tgz
  charts/ghost/charts/mariadb-0.2.17.tgz
  charts/gitea/Chart.lock
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
  charts/gitea/charts/mariadb-0.2.16.tgz
  charts/gitea/charts/mariadb-0.2.17.tgz
  charts/gitea/charts/postgres-0.2.15.tgz
  charts/gitea/charts/postgres-0.2.16.tgz
  charts/gitea/charts/redis-0.4.10.tgz
  charts/gitea/charts/redis-0.4.9.tgz
  charts/graylog/Chart.lock
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/charts/elasticsearch-0.1.104.tgz
  charts/graylog/charts/elasticsearch-0.1.106.tgz
  charts/graylog/charts/mongodb-0.3.6.tgz
  charts/graylog/charts/mongodb-0.3.8.tgz
  charts/nextcloud/Chart.lock
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
  charts/nextcloud/charts/mariadb-0.2.16.tgz
  charts/nextcloud/charts/mariadb-0.2.17.tgz
  charts/nextcloud/charts/postgres-0.2.15.tgz
  charts/nextcloud/charts/postgres-0.2.16.tgz
  charts/nextcloud/charts/redis-0.4.10.tgz
  charts/nextcloud/charts/redis-0.4.9.tgz
  charts/remark42/Chart.lock
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/RELEASENOTES.md
  charts/remark42/charts/redis-0.4.10.tgz
  charts/remark42/charts/redis-0.4.9.tgz
  charts/wordpress/Chart.lock
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
  charts/wordpress/charts/mariadb-0.2.16.tgz
  charts/wordpress/charts/mariadb-0.2.17.tgz
Labels: update

#831 Update ghost chart for Ghost 4.33.1
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#833 Update wordpress chart for Wordpress 5.9.0
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
Labels: update

#838 Upgrade ghost chart for Ghost 4.34.0
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#839 Update gitea chart for Gitea 1.15.11
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
Labels: update

#840 Update gitea chart for Gitea 1.16.0
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
Labels: update
