Repository groundhog2k/helm-charts, pull requests merged in 2023-12, with the labels that each got.

#1291 Updated ghost chart for Ghost 5.75.0
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#1292 Updated ghost chart for Ghost 5.75.1
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#1293 Updated garylog chart for Graylog 5.2.2
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
Labels: update

#1295 Updated nextcloiud chart for Nextcloud 28
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
Labels: update

#1296 Updated rabbitmq chart for RabbitMQ 3.11.27
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/RELEASENOTES.md
Labels: update

#1297 Updated ghost chart for Ghost 5.75.2
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
Labels: update

#1298 Updated gitea chart for Gitea 1.21.3
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
Labels: update

#1299 Updated wordpress chart for Wordpress 6.4.1
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
Labels: update

#1300 Updated wordpress chart for Wordpress 6.4.2
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
Labels: update

#1301 Updated mongodb chart for Mongodb 6.0.12
  charts/mongodb/Chart.yaml
  charts/mongodb/RELEASENOTES.md
Labels: update

#1302 Updated mongodb chart for MongoDB 7.0.4
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/RELEASENOTES.md
Labels: update

#1303 Updated nextcloud chart for Nextcloud 28.0.1
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
Labels: update

#1304 Updated rabbitmq chart for RabbitMQ 3.11.28
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/RELEASENOTES.md
Labels: update

#1306 rabbitmq - set additional service lables
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/extraservices.yaml
  charts/rabbitmq/templates/service.yaml
  charts/rabbitmq/values.yaml
Labels: feature

#1308 Updated rabbitmq chart for RabbitMQ 3.12.11 and additional service labels
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
Labels: feature, update

#1305 redis - additional service labels
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/RELEASENOTES.md
  charts/redis/templates/services.yaml
  charts/redis/values.yaml
Labels: feature

#1309 Added option to set Pod Topology Spread Constraints
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/RELEASENOTES.md
  charts/redis/templates/statefulset.yaml
  charts/redis/values.yaml
Labels: feature

#1310 Rabbitmq-0.7.13
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/statefulset.yaml
  charts/rabbitmq/values.yaml
Labels: feature

#1312 Renamed topology spread constraints
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/statefulset.yaml
  charts/rabbitmq/values.yaml
  charts/redis/Chart.yaml
  charts/redis/README.md
  charts/redis/RELEASENOTES.md
  charts/redis/templates/statefulset.yaml
  charts/redis/values.yaml
Labels: improvement

#1313 add ingressClassName
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/RELEASENOTES.md
  charts/commento/templates/ingress.yaml
  charts/commento/values.yaml
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
  charts/ghost/templates/ingress.yaml
  charts/ghost/values.yaml
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
  charts/gitea/templates/ingress.yaml
  charts/gitea/values.yaml
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/templates/ingress.yaml
  charts/graylog/values.yaml
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
  charts/nextcloud/templates/ingress.yaml
  charts/nextcloud/values.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/ingress.yaml
  charts/rabbitmq/values.yaml
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/RELEASENOTES.md
  charts/remark42/templates/ingress.yaml
  charts/remark42/values.yaml
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
  charts/wordpress/templates/ingress.yaml
  charts/wordpress/values.yaml
Labels: feature

#1315 Groundhog2k/issue1314
  charts/commento/.helmignore
  charts/commento/Chart.lock
  charts/commento/Chart.yaml
  charts/commento/README.md
  charts/commento/RELEASENOTES.md
  charts/commento/charts/postgres-0.2.26.tgz
  charts/commento/templates/_helpers.tpl
  charts/commento/templates/deployment.yaml
  charts/commento/templates/ingress.yaml
  charts/commento/templates/pdp.yaml
  charts/commento/templates/secureconfig.yaml
  charts/commento/templates/service.yaml
  charts/commento/templates/serviceaccount.yaml
  charts/commento/templates/tests/test-connection.yaml
  charts/commento/values.yaml
  charts/elasticsearch/.helmignore
  charts/elasticsearch/Chart.yaml
  charts/elasticsearch/README.md
  charts/elasticsearch/RELEASENOTES.md
  charts/elasticsearch/templates/_helpers.tpl
  charts/elasticsearch/templates/ingress.yaml
  charts/elasticsearch/templates/service-internal.yaml
  charts/elasticsearch/templates/service.yaml
  charts/elasticsearch/templates/serviceaccount.yaml
  charts/elasticsearch/templates/statefulset.yaml
  charts/elasticsearch/templates/tests/test-connection.yaml
  charts/elasticsearch/values.yaml
  charts/graylog/Chart.lock
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/charts/elasticsearch-0.1.106.tgz
  charts/graylog/charts/mongodb-0.5.19.tgz
  charts/graylog/charts/mongodb-0.5.20.tgz
  charts/graylog/templates/_helpers.tpl
  charts/graylog/values.yaml
Labels: update

#1317 Groundhog2k/issue1316
  charts/ghost/Chart.yaml
  charts/ghost/README.md
  charts/ghost/RELEASENOTES.md
  charts/ghost/templates/ingress.yaml
  charts/ghost/values.yaml
  charts/gitea/Chart.yaml
  charts/gitea/README.md
  charts/gitea/RELEASENOTES.md
  charts/gitea/templates/ingress.yaml
  charts/gitea/values.yaml
  charts/graylog/Chart.yaml
  charts/graylog/README.md
  charts/graylog/RELEASENOTES.md
  charts/graylog/templates/ingress.yaml
  charts/graylog/values.yaml
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
  charts/nextcloud/templates/ingress.yaml
  charts/nextcloud/values.yaml
  charts/nfs-client-provisioner/.helmignore
  charts/nfs-client-provisioner/Chart.yaml
  charts/nfs-client-provisioner/README.md
  charts/nfs-client-provisioner/ci/test-values.yaml
  charts/nfs-client-provisioner/templates/_helpers.tpl
  charts/nfs-client-provisioner/templates/clusterrole.yaml
  charts/nfs-client-provisioner/templates/clusterrolebinding.yaml
  charts/nfs-client-provisioner/templates/deployment.yaml
  charts/nfs-client-provisioner/templates/persistentvolume.yaml
  charts/nfs-client-provisioner/templates/persistentvolumeclaim.yaml
  charts/nfs-client-provisioner/templates/podsecuritypolicy.yaml
  charts/nfs-client-provisioner/templates/role.yaml
  charts/nfs-client-provisioner/templates/rolebinding.yaml
  charts/nfs-client-provisioner/templates/serviceaccount.yaml
  charts/nfs-client-provisioner/templates/storageclass.yaml
  charts/nfs-client-provisioner/values.yaml
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/ingress.yaml
  charts/rabbitmq/values.yaml
  charts/remark42/Chart.yaml
  charts/remark42/README.md
  charts/remark42/RELEASENOTES.md
  charts/remark42/templates/ingress.yaml
  charts/remark42/values.yaml
  charts/wordpress/Chart.yaml
  charts/wordpress/README.md
  charts/wordpress/RELEASENOTES.md
  charts/wordpress/templates/ingress.yaml
  charts/wordpress/values.yaml
Labels: improvement

#1319 Added additional annotation and labels for Nextcloud cron jobs
  charts/nextcloud/Chart.yaml
  charts/nextcloud/README.md
  charts/nextcloud/RELEASENOTES.md
  charts/nextcloud/templates/cronjobs.yaml
  charts/nextcloud/templates/defaultcronjobs.yaml
  charts/nextcloud/values.yaml
Labels: feature, improvement
