Repository groundhog2k/helm-charts, pull requests merged in 2025-08, with the labels that each got.

#1409 Fixed mounted volume name Fixes #1408
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/statefulset.yaml
Labels: bug

#1403 Implemented optional extra ports for the default RabbitMQ service
  charts/rabbitmq/Chart.yaml
  charts/rabbitmq/README.md
  charts/rabbitmq/RELEASENOTES.md
  charts/rabbitmq/templates/service.yaml
  charts/rabbitmq/templates/statefulset.yaml
  charts/rabbitmq/values.yaml
Labels: improvement

#1415 Added optional resources for initContainer
  charts/postgres/Chart.yaml
  charts/postgres/README.md
  charts/postgres/RELEASENOTES.md
  charts/postgres/templates/statefulset.yaml
  charts/postgres/values.yaml
Labels: improvement

#1418 Updated to Valkey 8.1.3, redis_exporter 1.75.0
  charts/valkey/Chart.yaml
  charts/valkey/README.md
  charts/valkey/RELEASENOTES.md
  charts/valkey/values.yaml
Labels: update

#1419 Add possibility for having resources limits/request in init container…
  charts/mongodb/Chart.yaml
  charts/mongodb/README.md
  charts/mongodb/RELEASENOTES.md
  charts/mongodb/templates/statefulset-arbiter.yaml
  charts/mongodb/templates/statefulset-hidden.yaml
  charts/mongodb/templates/statefulset.yaml
  charts/mongodb/values.yaml
Labels: improvement
